# Generated by Django 3.2.4 on 2021-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('web_address', models.DateField(null=True)),
                ('bookmark_pic', models.ImageField(blank=True, default='profile_default.png', null=True, upload_to='')),
            ],
        ),
    ]
