# Generated by Django 3.2.4 on 2021-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='web_address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
