# Generated by Django 3.2.4 on 2021-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211005_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='date_created',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
