# Generated by Django 3.2.4 on 2021-10-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
