# Generated by Django 3.2.4 on 2021-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_bookmark_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_pic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
