# Generated by Django 3.2.4 on 2021-10-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_bookmark_bookmark_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bookmark_pic',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='web_address',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
