# Generated by Django 3.2.4 on 2021-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211005_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmark_pic',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='web_address',
            new_name='page_url',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='summary',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='preview_image',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
