# Generated by Django 3.2.4 on 2021-10-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211006_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='decription',
            new_name='description',
        ),
    ]
