# Generated by Django 3.2.4 on 2021-10-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_decription_bookmark_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('bookmark', models.ManyToManyField(null=True, related_name='folders', to='backend.Bookmark')),
            ],
        ),
    ]
