# Generated by Django 3.2.4 on 2021-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='preview_image',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
