# Generated by Django 3.2.4 on 2021-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_bookmark_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='bookmark',
            field=models.ManyToManyField(related_name='folders', to='backend.Bookmark'),
        ),
    ]
