# Generated by Django 3.2.4 on 2021-10-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='bookmark',
        ),
    ]
