# Generated by Django 3.2.4 on 2021-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_tag_tag_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='domain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
