# Generated by Django 3.2.4 on 2021-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_bookmark_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='time_created',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
