# Generated by Django 3.2.4 on 2021-10-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20211015_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
